/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubmissionsIndexRouteImport } from './routes/submissions/index'
import { Route as ApprovalQueueIndexRouteImport } from './routes/approval-queue/index'
import { Route as SubmissionsNewRouteImport } from './routes/submissions/new'
import { Route as SubmissionsSubmissionIdRouteImport } from './routes/submissions/$submissionId'
import { Route as ApprovalQueueSubmissionIdRouteImport } from './routes/approval-queue/$submissionId'
import { Route as AdminWebhookSubscriptionsRouteImport } from './routes/admin/webhook-subscriptions'
import { Route as AdminProvisioningRouteImport } from './routes/admin/provisioning'
import { Route as AdminOwnershipRouteImport } from './routes/admin/ownership'
import { Route as AdminCostRouteImport } from './routes/admin/cost'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionsIndexRoute = SubmissionsIndexRouteImport.update({
  id: '/submissions/',
  path: '/submissions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalQueueIndexRoute = ApprovalQueueIndexRouteImport.update({
  id: '/approval-queue/',
  path: '/approval-queue/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionsNewRoute = SubmissionsNewRouteImport.update({
  id: '/submissions/new',
  path: '/submissions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionsSubmissionIdRoute = SubmissionsSubmissionIdRouteImport.update({
  id: '/submissions/$submissionId',
  path: '/submissions/$submissionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalQueueSubmissionIdRoute =
  ApprovalQueueSubmissionIdRouteImport.update({
    id: '/approval-queue/$submissionId',
    path: '/approval-queue/$submissionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminWebhookSubscriptionsRoute =
  AdminWebhookSubscriptionsRouteImport.update({
    id: '/admin/webhook-subscriptions',
    path: '/admin/webhook-subscriptions',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminProvisioningRoute = AdminProvisioningRouteImport.update({
  id: '/admin/provisioning',
  path: '/admin/provisioning',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOwnershipRoute = AdminOwnershipRouteImport.update({
  id: '/admin/ownership',
  path: '/admin/ownership',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCostRoute = AdminCostRouteImport.update({
  id: '/admin/cost',
  path: '/admin/cost',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/cost': typeof AdminCostRoute
  '/admin/ownership': typeof AdminOwnershipRoute
  '/admin/provisioning': typeof AdminProvisioningRoute
  '/admin/webhook-subscriptions': typeof AdminWebhookSubscriptionsRoute
  '/approval-queue/$submissionId': typeof ApprovalQueueSubmissionIdRoute
  '/submissions/$submissionId': typeof SubmissionsSubmissionIdRoute
  '/submissions/new': typeof SubmissionsNewRoute
  '/approval-queue/': typeof ApprovalQueueIndexRoute
  '/submissions/': typeof SubmissionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/cost': typeof AdminCostRoute
  '/admin/ownership': typeof AdminOwnershipRoute
  '/admin/provisioning': typeof AdminProvisioningRoute
  '/admin/webhook-subscriptions': typeof AdminWebhookSubscriptionsRoute
  '/approval-queue/$submissionId': typeof ApprovalQueueSubmissionIdRoute
  '/submissions/$submissionId': typeof SubmissionsSubmissionIdRoute
  '/submissions/new': typeof SubmissionsNewRoute
  '/approval-queue': typeof ApprovalQueueIndexRoute
  '/submissions': typeof SubmissionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/cost': typeof AdminCostRoute
  '/admin/ownership': typeof AdminOwnershipRoute
  '/admin/provisioning': typeof AdminProvisioningRoute
  '/admin/webhook-subscriptions': typeof AdminWebhookSubscriptionsRoute
  '/approval-queue/$submissionId': typeof ApprovalQueueSubmissionIdRoute
  '/submissions/$submissionId': typeof SubmissionsSubmissionIdRoute
  '/submissions/new': typeof SubmissionsNewRoute
  '/approval-queue/': typeof ApprovalQueueIndexRoute
  '/submissions/': typeof SubmissionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/cost'
    | '/admin/ownership'
    | '/admin/provisioning'
    | '/admin/webhook-subscriptions'
    | '/approval-queue/$submissionId'
    | '/submissions/$submissionId'
    | '/submissions/new'
    | '/approval-queue/'
    | '/submissions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/cost'
    | '/admin/ownership'
    | '/admin/provisioning'
    | '/admin/webhook-subscriptions'
    | '/approval-queue/$submissionId'
    | '/submissions/$submissionId'
    | '/submissions/new'
    | '/approval-queue'
    | '/submissions'
  id:
    | '__root__'
    | '/'
    | '/admin/cost'
    | '/admin/ownership'
    | '/admin/provisioning'
    | '/admin/webhook-subscriptions'
    | '/approval-queue/$submissionId'
    | '/submissions/$submissionId'
    | '/submissions/new'
    | '/approval-queue/'
    | '/submissions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminCostRoute: typeof AdminCostRoute
  AdminOwnershipRoute: typeof AdminOwnershipRoute
  AdminProvisioningRoute: typeof AdminProvisioningRoute
  AdminWebhookSubscriptionsRoute: typeof AdminWebhookSubscriptionsRoute
  ApprovalQueueSubmissionIdRoute: typeof ApprovalQueueSubmissionIdRoute
  SubmissionsSubmissionIdRoute: typeof SubmissionsSubmissionIdRoute
  SubmissionsNewRoute: typeof SubmissionsNewRoute
  ApprovalQueueIndexRoute: typeof ApprovalQueueIndexRoute
  SubmissionsIndexRoute: typeof SubmissionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submissions/': {
      id: '/submissions/'
      path: '/submissions'
      fullPath: '/submissions/'
      preLoaderRoute: typeof SubmissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approval-queue/': {
      id: '/approval-queue/'
      path: '/approval-queue'
      fullPath: '/approval-queue/'
      preLoaderRoute: typeof ApprovalQueueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submissions/new': {
      id: '/submissions/new'
      path: '/submissions/new'
      fullPath: '/submissions/new'
      preLoaderRoute: typeof SubmissionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submissions/$submissionId': {
      id: '/submissions/$submissionId'
      path: '/submissions/$submissionId'
      fullPath: '/submissions/$submissionId'
      preLoaderRoute: typeof SubmissionsSubmissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approval-queue/$submissionId': {
      id: '/approval-queue/$submissionId'
      path: '/approval-queue/$submissionId'
      fullPath: '/approval-queue/$submissionId'
      preLoaderRoute: typeof ApprovalQueueSubmissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/webhook-subscriptions': {
      id: '/admin/webhook-subscriptions'
      path: '/admin/webhook-subscriptions'
      fullPath: '/admin/webhook-subscriptions'
      preLoaderRoute: typeof AdminWebhookSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/provisioning': {
      id: '/admin/provisioning'
      path: '/admin/provisioning'
      fullPath: '/admin/provisioning'
      preLoaderRoute: typeof AdminProvisioningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ownership': {
      id: '/admin/ownership'
      path: '/admin/ownership'
      fullPath: '/admin/ownership'
      preLoaderRoute: typeof AdminOwnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cost': {
      id: '/admin/cost'
      path: '/admin/cost'
      fullPath: '/admin/cost'
      preLoaderRoute: typeof AdminCostRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminCostRoute: AdminCostRoute,
  AdminOwnershipRoute: AdminOwnershipRoute,
  AdminProvisioningRoute: AdminProvisioningRoute,
  AdminWebhookSubscriptionsRoute: AdminWebhookSubscriptionsRoute,
  ApprovalQueueSubmissionIdRoute: ApprovalQueueSubmissionIdRoute,
  SubmissionsSubmissionIdRoute: SubmissionsSubmissionIdRoute,
  SubmissionsNewRoute: SubmissionsNewRoute,
  ApprovalQueueIndexRoute: ApprovalQueueIndexRoute,
  SubmissionsIndexRoute: SubmissionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
