/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubmissionsIndexRouteImport } from './routes/submissions/index'
import { Route as SubmissionsNewRouteImport } from './routes/submissions/new'
import { Route as SubmissionsSubmissionIdRouteImport } from './routes/submissions/$submissionId'
import { Route as AdminWebhookSubscriptionsRouteImport } from './routes/admin/webhook-subscriptions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionsIndexRoute = SubmissionsIndexRouteImport.update({
  id: '/submissions/',
  path: '/submissions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionsNewRoute = SubmissionsNewRouteImport.update({
  id: '/submissions/new',
  path: '/submissions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionsSubmissionIdRoute = SubmissionsSubmissionIdRouteImport.update({
  id: '/submissions/$submissionId',
  path: '/submissions/$submissionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWebhookSubscriptionsRoute =
  AdminWebhookSubscriptionsRouteImport.update({
    id: '/admin/webhook-subscriptions',
    path: '/admin/webhook-subscriptions',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/webhook-subscriptions': typeof AdminWebhookSubscriptionsRoute
  '/submissions/$submissionId': typeof SubmissionsSubmissionIdRoute
  '/submissions/new': typeof SubmissionsNewRoute
  '/submissions/': typeof SubmissionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/webhook-subscriptions': typeof AdminWebhookSubscriptionsRoute
  '/submissions/$submissionId': typeof SubmissionsSubmissionIdRoute
  '/submissions/new': typeof SubmissionsNewRoute
  '/submissions': typeof SubmissionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/webhook-subscriptions': typeof AdminWebhookSubscriptionsRoute
  '/submissions/$submissionId': typeof SubmissionsSubmissionIdRoute
  '/submissions/new': typeof SubmissionsNewRoute
  '/submissions/': typeof SubmissionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/webhook-subscriptions'
    | '/submissions/$submissionId'
    | '/submissions/new'
    | '/submissions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/webhook-subscriptions'
    | '/submissions/$submissionId'
    | '/submissions/new'
    | '/submissions'
  id:
    | '__root__'
    | '/'
    | '/admin/webhook-subscriptions'
    | '/submissions/$submissionId'
    | '/submissions/new'
    | '/submissions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminWebhookSubscriptionsRoute: typeof AdminWebhookSubscriptionsRoute
  SubmissionsSubmissionIdRoute: typeof SubmissionsSubmissionIdRoute
  SubmissionsNewRoute: typeof SubmissionsNewRoute
  SubmissionsIndexRoute: typeof SubmissionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submissions/': {
      id: '/submissions/'
      path: '/submissions'
      fullPath: '/submissions/'
      preLoaderRoute: typeof SubmissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submissions/new': {
      id: '/submissions/new'
      path: '/submissions/new'
      fullPath: '/submissions/new'
      preLoaderRoute: typeof SubmissionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submissions/$submissionId': {
      id: '/submissions/$submissionId'
      path: '/submissions/$submissionId'
      fullPath: '/submissions/$submissionId'
      preLoaderRoute: typeof SubmissionsSubmissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/webhook-subscriptions': {
      id: '/admin/webhook-subscriptions'
      path: '/admin/webhook-subscriptions'
      fullPath: '/admin/webhook-subscriptions'
      preLoaderRoute: typeof AdminWebhookSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminWebhookSubscriptionsRoute: AdminWebhookSubscriptionsRoute,
  SubmissionsSubmissionIdRoute: SubmissionsSubmissionIdRoute,
  SubmissionsNewRoute: SubmissionsNewRoute,
  SubmissionsIndexRoute: SubmissionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
