// pattern: Imperative Shell — fetches findings, renders NudgeCard list.
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { listFindings, recordDecision } from './api';
import { NudgeCard } from './nudge-card';
import type { Decision, FindingWithDecision } from './types';

// ─── Props ─────────────────────────────────────────────────────────────────────

type NudgesPanelProps = {
  submissionId: string;
};

// ─── Severity sort order ───────────────────────────────────────────────────────

const SEVERITY_ORDER: Record<string, number> = {
  error: 0,
  warn: 1,
  info: 2,
};

function sortBySeverity(findings: FindingWithDecision[]): FindingWithDecision[] {
  return [...findings].sort((a, b) => {
    const ao = SEVERITY_ORDER[a.severity] ?? 99;
    const bo = SEVERITY_ORDER[b.severity] ?? 99;
    return ao - bo;
  });
}

// ─── Component ─────────────────────────────────────────────────────────────────

/**
 * NudgesPanel — fetches detection findings for a submission and renders them as
 * NudgeCard components, grouped error-first, warn, then info.
 *
 * Query key: ['findings', submissionId] — invalidated after each decision so the
 * panel refreshes and the decided card gains its "Decided:" state.
 */
export function NudgesPanel({ submissionId }: NudgesPanelProps) {
  const queryClient = useQueryClient();

  const { data: findings, isLoading, error } = useQuery({
    queryKey: ['findings', submissionId],
    queryFn: () => listFindings(submissionId),
    retry: 1,
  });

  async function handleDecision(
    findingId: string,
    decision: Decision,
    notes: string | undefined,
    /** Per-intent idempotency key generated by NudgeCard via useRef. */
    idempotencyKey: string,
  ) {
    await recordDecision(submissionId, findingId, decision, notes, idempotencyKey);
    await queryClient.invalidateQueries({ queryKey: ['findings', submissionId] });
  }

  if (isLoading) {
    return (
      <section aria-label="Detection nudges">
        <p className="text-sm text-gray-600">Loading findings…</p>
      </section>
    );
  }

  if (error) {
    return (
      <section aria-label="Detection nudges">
        <div className="rounded-md bg-red-50 p-4">
          <p className="text-sm text-red-800">
            {error instanceof Error ? error.message : 'Failed to load findings'}
          </p>
        </div>
      </section>
    );
  }

  if (!findings || findings.length === 0) {
    return (
      <section aria-label="Detection nudges">
        <p className="text-sm text-gray-600">No issues detected.</p>
      </section>
    );
  }

  const sorted = sortBySeverity(findings);

  return (
    <section aria-label="Detection nudges">
      <h3 className="text-base font-semibold text-gray-800 mb-3">
        Detection Findings ({findings.length})
      </h3>
      <div className="space-y-3">
        {sorted.map((finding) => (
          <NudgeCard
            key={finding.id}
            finding={finding}
            onDecision={(decision, notes, idempotencyKey) =>
              handleDecision(finding.id, decision, notes, idempotencyKey)
            }
          />
        ))}
      </div>
    </section>
  );
}
